apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-arena-meldeplikt-adapter
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: {{ image }}
  port: 8080
  prometheus:
    enabled: true
    path: /internal/metrics
  liveness:
    path: /internal/isalive
  readiness:
    path: /internal/isready
  replicas:
    min: 2
    max: 4
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  ingresses:
    {{#each ingresses as |url|}}
     - {{ url }}
    {{/each}}
  secureLogs:
    enabled: true
  env:
    - name: MELDEKORTSERVICE_URL
      value: 'https://{{ meldekortserviceHost }}/meldekortservice/'
    - name: MELDEKORTSERVICE_SCOPE
      value: {{ meldekortserviceScope }}
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: dp-rapportering
    outbound:
      external:
        - host: {{ meldekortserviceHost }}
