apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-arena-meldeplikt-adapter
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: "{{ image }}"
  port: 8080
  prometheus:
    enabled: true
    path: /internal/metrics
  liveness:
    path: /internal/isalive
  readiness:
    path: /internal/isready
  replicas:
    min: 2
    max: 4
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  ingresses:
    {{#each ingresses as |url|}}
     - {{ url }}
    {{/each}}
  secureLogs:
    enabled: true
  env:
    - name: MELDEKORTSERVICE_URL
      value: 'https://{{ meldekortserviceHost }}/meldekortservice/api'
    - name: MELDEKORTSERVICE_AUDIENCE
      value: "{{ meldekortserviceAudience }}"
    - name: MELDEKORTKONTROLL_URL
      value: 'https://{{ meldekortkontrollHost }}/api/v1/kontroll'
    - name: MELDEKORTKONTROLL_AUDIENCE
      value: "{{ meldekortkontrollAudience }}"
    - name: JDK_JAVA_OPTIONS # Bytter GC og lar JVMen se at det er flere CPU kjerner
      value: -XX:+UseParallelGC -XX:ActiveProcessorCount=4
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
      allowAllUsers: true
  accessPolicy:
    inbound:
      rules:
        - application: dp-rapportering
        - application: dp-rapportering-personregister
        - application: dp-meldekortregister
        - application: tokenx-token-generator
          namespace: aura
          cluster: dev-gcp
        - application: azure-token-generator
          namespace: nais
          cluster: dev-gcp
    outbound:
      external:
        - host: "{{ meldekortserviceHost }}"
        - host: "{{ meldekortkontrollHost }}"
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
    autoInstrumentation:
      enabled: true
      runtime: java
