/*
 * This source file was generated by the Gradle 'init' task
 */
package no.nav.dagpenger.arenameldepliktadapter

import kotlin.test.Test

class AppTest {
    @Test
    fun appHasAGreeting() {

    }
}
